# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-29 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '\u57f9\u8bad\u673a\u6784'), (1, '\u9ad8\u6821'), (2, '\u4e2a\u4eba')], default=0, max_length=20, verbose_name='\u673a\u6784\u7c7b\u578b'),
        ),
    ]
