# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-31 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
